# Generated by Django 3.2.5 on 2021-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'คณิตศาสตร์'), ('sci', 'วิทยาศาสตร์'), ('art', 'ศิลปะ'), ('eng', 'ภาษาอังกฤษ'), ('physics', 'ฟิสิกส์'), ('bio', 'ชีวะวิทยา')], default='math', max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
